### ISSUE TITLE
Doesn't compile due to deleted method setBlockedGesturalNavigation

### ISSUE THREAD

**Issue by Logan-Developer** [Evolution-X-AOSP/packages_apps_GamingMode#5]
Hello,

I just want to signal that this package can't be compiled anymore due to this commit, in Framework_base:
https://github.com/Evolution-X/frameworks_base/commit/ed3c5760148c5e378a7beee8f01d0b525e2cba64

(setBlockedGesturalNavigation method removed)

![image](https://user-images.githubusercontent.com/42945163/153078541-e7cd602c-470a-4e7f-b979-b75836f0ddf5.png)

**Comment by LucyfMorning** [comment]
I confirm this information ... I also tried to build with the February base and this error occurred with me

**Comment by joeyhuab** [comment]
Should be fixed now.
